name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy_Frontend:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy frontend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/electrode-deploy/electrode-fe
            git pull origin main

            cd ..
            docker-compose build frontend
            docker-compose up -d frontend

            docker image prune -f
            docker ps
